{% set name = "requests-ftp" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7504ceb5cba8a5c0135ed738596820a78c5f2be92d79b29f96ba99b183d8057a

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install .


requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - requests >=2.3.0

test:
  imports:
    - requests_ftp

about:
  home: https://github.com/Lukasa/requests-ftp
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'An FTP transport adapter for use with the Python Requests library'
  dev_url: https://github.com/Lukasa/requests-ftp

extra:
  recipe-maintainers:
    - mariusvniekerk
