travis:
  secure:
    BINSTAR_TOKEN: Fpn3T7SiLGE6Ss7bjsfL3od/jveF9NpaCSw5TTOx3vACK1Lb6KF6HG6kug8DBlMGLqQZVonuK1oQxwZggb2dDNDitQlkX20bpFxzakH/5FVTPin3nxfiVLUt/AfGX46ArUPKL650TaHaoAAM9dIGsfWZcodvbHkbKgDuS22YGI4J6TDwEGu9KnmfaLiztRgIxXDnzl6NgV/d0OuHkIqcJsQY5Lf6ifMGOlScG7YhnBj8myKBq/kwWyWNmSCkjuTIrtZ1wmuNb29Qz05MRfr3Hp067N6cCZRm1iagkYYJ+BjgmLiYtva7AWniYzMDTWEPuWPfXSjiLEdyrTS1th71WKlBbp6xyUkKb5W6Ky5AqsAOS89NcCg7lEizmyR6vGynnrB9GVggD/S+edZO9iZkZB10LFqjQYh/GzPcTaMtN1LsZUiE522yp7HeQGYEiEXLmrWzG0cPNkEc/YP4YpmJha1OLh8D7k0BfcJJ+/L1ICLEyg2UQ3Q/ztYSNFZyVPiLAbdgpcskEx+/TZJy8vhoofCM7upfJw5+k7GnOs6CY2QIFHKAwW/KzZ4t16fYq5IuLTbq3u8Ljt9U9QdkadfD9FjXwlYJ4uRO73IGzR6BUd84QOHvDB3j7b8DHiNXbkTVwNKLXlz1F5SSwe7ujE7HzN60s6bemMZ/wUH6UhX5m0A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
